import { createClient } from "@supabase/supabase-js";

const supabaseUrl = "https://ivbrcjjwcyzafvepypfj.supabase.co";
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2YnJjamp3Y3l6YWZ2ZXB5cGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NDkwMjMsImV4cCI6MjA3NjEyNTAyM30.55qFRDRF3YCP2PJttZTQWzSOx6E059sv9_iyfSlwwp4";
const SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2YnJjamp3Y3l6YWZ2ZXB5cGZqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDU0OTAyMywiZXhwIjoyMDc2MTI1MDIzfQ.ffzm3cuBRLF_d9J2o5fxObB159UgX-RB2y6zvB5o82Y"
export const supabase = createClient(supabaseUrl, supabaseAnonKey);
